Repository arcosuc3m/grppi, pull requests merged in 2018-02, with the labels that each got.

#315 FF support for mapreduce
  include/dyn/dynamic_execution.h
  include/ff/parallel_execution_ff.h
  unit_tests/mapreduce.cpp
  unit_tests/reduce.cpp
Labels: enhancement

#314 FF suport for reduce pattern
  include/dyn/dynamic_execution.h
  include/ff/parallel_execution_ff.h
  unit_tests/reduce.cpp
Labels: enhancement

#326 Interface Evolution
  include/common/iterator_traits.h
  include/map.h
  include/mapreduce.h
  include/reduce.h
  include/stencil.h
  samples/farm/capitalize/main.cpp
  samples/map/add_sequences/main.cpp
  samples/map/daxpy/main.cpp
  samples/stencil/matrix_mult/main.cpp
  unit_tests/map.cpp
  unit_tests/mapreduce.cpp
  unit_tests/reduce.cpp
  unit_tests/stencil.cpp
Labels: enhancement

#333 Deprecated old divide/conquer interface
  include/divideconquer.h
  include/dyn/dynamic_execution.h
  include/native/parallel_execution_native.h
  include/omp/parallel_execution_omp.h
  include/seq/sequential_execution.h
  include/tbb/parallel_execution_tbb.h
Labels: enhancement

#330 FastFlow pipeline implementation
  CREDITS.txt
  include/common/reduce_pattern.h
  include/dyn/dynamic_execution.h
  include/ff/detail/fastflow_allocator.h
  include/ff/detail/filter_nodes.h
  include/ff/detail/iteration_nodes.h
  include/ff/detail/ordered_stream_filter.h
  include/ff/detail/ordered_stream_reduce.h
  include/ff/detail/pipeline_impl.h
  include/ff/detail/reduce_nodes.h
  include/ff/detail/simple_node.h
  include/ff/detail/unordered_stream_filter.h
  include/ff/detail/unordered_stream_reduce.h
  include/ff/parallel_execution_ff.h
  include/tbb/parallel_execution_tbb.h
  unit_tests/context.cpp
  unit_tests/farm.cpp
  unit_tests/farm_pipeline_composition.cpp
  unit_tests/pipeline.cpp
  unit_tests/stream_filter.cpp
  unit_tests/stream_iteration.cpp
  unit_tests/stream_reduce.cpp
Labels: enhancement

#339 Updated documentation
  README.md
  doc/context.md
  doc/install-notes.md
Labels: documentation

#338 Enable -Wno-deprecated-declarations for *_legacy.cpp
  unit_tests/CMakeLists.txt
Labels: testing, toolchain
